Repository spryker-sdk/sdk, pull requests merged in 2022-08, with the labels that each got.

#171 SDK-815: Moved sdk-task-bundle from submodules to composer suggestion.
  composer.json
  docs/build.md
Labels: bug

#173 SDK-809: Added logger to log errors during submodules installation.
  composer.json
  composer.lock
  config/bundles.php
  config/packages/monolog.yaml
  src/Infrastructure/Resources/config/services.yaml
  src/Infrastructure/Service/TasksRepositoryInstaller.php
  src/Presentation/Console/Command/InitSdkCommand.php
  symfony.lock
Labels: bug

#190 SDK-756: Improved description for the 'validation:php:deprecations-check' task.
  src/Extension/Task/DeprecationsCheckTask.yaml
Labels: dev-qa done

#183 SDK-832 refactor workflow listener
  composer.json
  composer.lock
  extension/Hello/Resources/config/workflow.yaml
  src/Extension/Resources/config/services.yaml
  src/Extension/Workflow/TransitionBooleanResolver.php
  src/Infrastructure/Event/Workflow/WorkflowTransitionListener.php
  src/Infrastructure/Resources/config/services.yaml
  src/Infrastructure/Service/WorkflowTransitionResolverRegistry.php
  tests/Sdk/Unit/Infrastructure/Event/Workflow/WorkflowTransitionListenerTest.php
  tests/Sdk/Unit/Infrastructure/Service/WorkflowTransitionResolverRegistryTest.php
Labels: dev-qa done

#193 SDK-853: Fixed extension paths
  app/Kernel.php
  composer.json
  extension/Hello/config/services.yaml
  extension/Hello/config/workflow.yaml
  extension/Hello/src/DependencyInjection/HelloExtension.php
  extension/Hello/src/HelloBundle.php
  extension/Hello/src/Task/ByeWorldTask.yaml
  extension/Hello/src/Task/Command/GreeterCommand.php
  extension/Hello/src/Task/Command/HelloPhpCommand.php
  extension/Hello/src/Task/HelloPhpTask.php
  extension/Hello/src/Task/HelloStagedTaskSet.php
  extension/Hello/src/Task/HelloTaskSet.yaml
  extension/Hello/src/Task/HelloWorldTask.yaml
  src/Extension/Setting/settings.yaml
  src/Infrastructure/Repository/TaskYamlRepository.php
  src/Infrastructure/Service/ValueResolverRegistry.php
  tests/Sdk/Unit/Infrastructure/Repository/TaskYamlRepositoryTest.php
Labels: bug

#192 SDK-841 fix code-sniffer tasks sets
  src/Extension/Resources/config/task/AppValidationTaskSet.yaml
  src/Extension/Resources/config/task/PbcCodesnifferFixerTask.yaml
  src/Extension/Resources/config/task/PbcCodesnifferTask.yaml
  src/Extension/Resources/config/task/PhpStanTask.yaml
Labels: bug, dev-qa done

#189 SDK-844 fix workflow command and docs
  bin/spryker-sdk.sh
  docker-compose.yml
  docs/workflow.md
  src/Presentation/Console/Command/ShowWorkflowCommand.php
  src/Presentation/Console/Resources/config/services.yaml
Labels: bug, documentation, dev-qa done

#191 SDK-851: Introduced convention for the sdk contracts.
  docs/conventions.md
Labels: documentation, dev-qa done
