Repository spryker-sdk/sdk, pull requests merged in 2022-09, with the labels that each got.

#184 SDK-834 remove symfony 6 packages
  .github/workflows/ci.yml
  composer.json
  composer.lock
  symfony.lock
Labels: dev-qa done

#181 SDK-813: break down task set
  config/packages/workflow.yaml
  src/Extension/Task/AcpAppAsyncApiFullFlowTaskSet.yaml
  src/Extension/Task/AcpAppOpenApiFullFlowTaskSet.yaml
Labels: dev-qa done

#206 SDK-924: Moved phpstan `path` config to the `phpstan.neon` file.
  composer.json
  phpstan.neon
  src/Extension/Resources/config/task/AcpAppAsyncApiFullFlowTaskSet.yaml
  src/Extension/Resources/config/task/AcpAppOpenApiFullFlowTaskSet.yaml
Labels: bug, dev-qa done

#196 SDK-812: Added interactive workflow transition resolver.
  extension/Hello/config/workflow.yaml
  src/Extension/Exception/UniqueValueException.php
  src/Extension/Resources/config/services.yaml
  src/Extension/Workflow/InteractionAnswerBasedTransitionResolver.php
  src/Infrastructure/Event/Workflow/WorkflowTransitionListener.php
  src/Presentation/Console/Command/RunWorkflowCommand.php
  src/Presentation/Console/Resources/config/services.yaml
  tests/Sdk/Unit/Extension/Workflow/InteractionAnswerBasedTransitionResolverTest.php
Labels: dev-qa done

#197 SDK-847 Refactored `CliValueResolver`.
  src/Core/Domain/Entity/Setting.php
  src/Core/Domain/Enum/ValueTypeEnum.php
  src/Extension/ValueResolver/AppPhpVersionValueResolver.php
  src/Extension/ValueResolver/AppTypeValueResolver.php
  src/Extension/ValueResolver/BusinessModelValueResolver.php
  src/Extension/ValueResolver/ConfigPathValueResolver.php
  src/Extension/ValueResolver/ModuleValueResolver.php
  src/Extension/ValueResolver/NamespaceValueResolver.php
  src/Extension/ValueResolver/OptionValueResolver.php
  src/Extension/ValueResolver/PCSystemValueResolver.php
  src/Extension/ValueResolver/SdkDirectoryValueResolver.php
  src/Extension/ValueResolver/SprykCodeLevelValueResolver.php
  src/Extension/ValueResolver/StaticValueResolver.php
  src/Infrastructure/Resources/config/services.yaml
  src/Infrastructure/Service/ActionApprover.php
  src/Infrastructure/Service/ValueReceiver/CliInteractionProcessor.php
  src/Infrastructure/Service/ValueReceiver/QuestionFactory/ArrayQuestionFactory.php
  src/Infrastructure/Service/ValueReceiver/QuestionFactory/BooleanQuestionFactory.php
  src/Infrastructure/Service/ValueReceiver/QuestionFactory/PathQuestionFactory.php
  src/Infrastructure/Service/ValueReceiver/QuestionFactory/QuestionFactoryInterface.php
  src/Infrastructure/Service/ValueReceiver/QuestionFactory/StringQuestionFactory.php
  src/Infrastructure/Service/ValueReceiver/QuestionFactoryRegistry.php
  src/Infrastructure/Service/WorkflowRunner.php
  src/Presentation/Console/Command/InitProjectCommand.php
  src/Presentation/Console/Command/RunWorkflowCommand.php
  src/Presentation/Console/Command/ShowWorkflowCommand.php
  tests/Sdk/Unit/Infrastructure/Service/ValueReceiver/CliInteractionProcessorTest.php
  tests/Sdk/Unit/Infrastructure/Service/ValueReceiver/QuestionFactory/ArrayQuestionFactoryTest.php
  tests/Sdk/Unit/Infrastructure/Service/ValueReceiver/QuestionFactory/BooleanQuestionFactoryTest.php
  tests/Sdk/Unit/Infrastructure/Service/ValueReceiver/QuestionFactory/PathQuestionFactoryTest.php
  tests/Sdk/Unit/Infrastructure/Service/ValueReceiver/QuestionFactory/StringQuestionFactoryTest.php
  tests/Sdk/Unit/Infrastructure/Service/ValueReceiver/QuestionFactoryRegistryTest.php
Labels: improvement

#217 SDK-976: Fixed format for workflow and report dir if project doesn't …
  src/Core/Application/Dependency/DefaultContextReceiverInterface.php
  src/Core/Application/Resources/config/services.yaml
  src/Core/Application/Service/ContextFactory.php
  src/Extension/ValueResolver/ReportDirValueResolver.php
  src/Infrastructure/Resources/config/services.yaml
  src/Infrastructure/Service/DefaultContextReceiver.php
  src/Presentation/Console/Command/RunTaskWrapperCommand.php
  tests/Sdk/Unit/Core/Application/Service/ContextFactoryTest.php
Labels: dev-qa done

#207 SDK-899 extend the task set
  composer.json
  composer.lock
  docs/lifecycle_management.md
  docs/task_set.md
  extension/Hello/src/Task/HelloStagedTaskSet.php
  src/Core/Domain/Enum/ValueTypeEnum.php
  src/Core/Domain/ValueObject/ConfigurableCommand.php
  src/Extension/Resources/config/task/AcpAppAsyncApiCreateTaskSet.yaml
  src/Extension/Resources/config/task/AcpAppAsyncApiFullFlowTaskSet.yaml
  src/Extension/Resources/config/task/AcpAppOpenApiFullFlowTaskSet.yaml
  src/Extension/Resources/config/task/AppValidationTaskSet.yaml
  src/Extension/Resources/config/task/CodesnifferTaskSet.yaml
  src/Extension/Resources/config/task/PhpMdTask.yaml
  src/Extension/Resources/config/task/SnifferTaskSet.yaml
  src/Infrastructure/Dto/TaskSetOverrideMapDto.php
  src/Infrastructure/Repository/TaskRepository.php
  src/Infrastructure/Repository/TaskYamlRepository.php
  src/Infrastructure/Resources/config/services.yaml
  src/Infrastructure/Service/TaskManager.php
  src/Infrastructure/Service/TaskOptionBuilder.php
  src/Infrastructure/Service/TaskSet/TaskFromTaskSetBuilder.php
  src/Infrastructure/Service/TaskSet/TaskFromTaskSetBuilderInterface.php
  src/Infrastructure/Service/TaskSet/TaskFromYamlTaskSetBuilder.php
  src/Infrastructure/Service/TaskSet/TaskFromYamlTaskSetBuilderInterface.php
  src/Infrastructure/Service/TaskSet/TaskSetCommandsBuilder.php
  src/Infrastructure/Service/TaskSet/TaskSetOverrideMap/TaskSetOverrideMapDtoBuilder.php
  src/Infrastructure/Service/TaskSet/TaskSetOverrideMap/TaskSetOverrideMapDtoBuilderFactory.php
  src/Infrastructure/Service/TaskSet/TaskSetOverrideMap/TaskSetOverrideMapDtoFactory.php
  src/Infrastructure/Service/TaskSet/TaskSetPlaceholdersBuilder.php
  src/Infrastructure/Service/TaskSet/Yaml/TaskSetCommandsFactory.php
  src/Infrastructure/Service/TaskSet/Yaml/TaskSetOverrideMapFactory.php
  src/Infrastructure/Service/TaskSet/Yaml/TaskSetPlaceholdersFactory.php
  src/Infrastructure/Service/ValueReceiver/QuestionFactory/IntQuestionFactory.php
  src/Infrastructure/Service/ValueReceiver/QuestionFactory/StringQuestionFactory.php
  tests/Sdk/Unit/Infrastructure/Repository/TaskYamlRepositoryTest.php
  tests/Sdk/Unit/Infrastructure/Service/TaskManagerTest.php
  tests/Sdk/Unit/Infrastructure/Service/TaskSet/TaskFromTaskSetBuilderTest.php
  tests/Sdk/Unit/Infrastructure/Service/TaskSet/TaskFromYamlTaskSetBuilderTest.php
  tests/Sdk/Unit/Infrastructure/Service/TaskSet/TaskSetCommandsBuilderTest.php
  tests/Sdk/Unit/Infrastructure/Service/TaskSet/TaskSetPlaceholdersBuilderTest.php
Labels: dev-qa done

#219 SDK-977 workflow issue fix
  infrastructure/sdk.Dockerfile
Labels: dev-qa done

#224 SDK-984 override version command
  bin/spryker-sdk.sh
Labels: bug, dev-qa done
