Repository spryker-sdk/sdk, pull requests merged in 2022-11, with the labels that each got.

#247 SDK-865: Added documentation for REST api
  docs/conventions.md
Labels: documentation

#242 SDK-866: Introduce a docker environment for the Web server. Introduce SdkRestApiBundle with http endpoint.
  bin/spryker-sdk.sh
  codeception.yml
  composer.json
  composer.lock
  config/bundles.php
  config/git/pre-commit
  config/packages/nelmio_api_doc.yaml
  config/routes.yaml
  config/routes/nelmio_api_doc.yaml
  docker-compose.rest-api.dev.yaml
  docs/conventions.md
  docs/rest_api.md
  infrastructure/debug/php/69-xdebug.ini
  infrastructure/sdk.debug.Dockerfile
  infrastructure/web/nginx.Dockerfile
  infrastructure/web/nginx/default.conf
  infrastructure/web/php-fpm.Dockerfile
  infrastructure/web/php-fpm.dev.Dockerfile
  phpcs.xml
  src/Core/Application/Dependency/AppVersionFetcherInterface.php
  src/Core/Application/Resources/config/services.yaml
  src/Core/Application/Version/AppVersionFetcher.php
  src/Infrastructure/Event/Request/JsonRequestListener.php
  src/Infrastructure/Resources/config/services.yaml
  src/Infrastructure/Service/CommandRunner/LocalCliRunner.php
  src/Infrastructure/Version/FileAppVersionFetcher.php
  src/Presentation/RestApi/ApiDoc/TaskApiDocDescriber.php
  src/Presentation/RestApi/Controller/v1/HelloController.php
  src/Presentation/RestApi/Controller/v1/IndexController.php
  src/Presentation/RestApi/Controller/v1/SdkInitProjectController.php
  src/Presentation/RestApi/Controller/v1/SdkInitSdkController.php
  src/Presentation/RestApi/Controller/v1/TaskController.php
  src/Presentation/RestApi/DependencyInjection/SprykerSdkRestApiExtension.php
  src/Presentation/RestApi/Executor/Task/RestApiTaskExecutor.php
  src/Presentation/RestApi/Resources/config/routing_v1.yaml
  src/Presentation/RestApi/Resources/config/services.yaml
  src/Presentation/RestApi/SprykerSdkRestApiBundle.php
  symfony.lock
  tests/Sdk/Acceptance/Presentation/RestApi/Controller/v1/HelloControllerCest.php
  tests/Sdk/Unit/Presentation/RestApi/DependencyInjection/SprykerSdkRestApiExtensionTest.php
  tests/Sdk/Unit/Presentation/RestApi/SprykerSdkRestApiBundleTest.php
  tests/_support/Helper/RestApiServerHelper.php
Labels: epic

#271 SDK-00: Fixed foc typo.
  docs/extending_the_sdk.md
Labels: documentation

#272 SDK-00: extend sdk doc fix.
  docs/extending_the_sdk.md
Labels: documentation

#273 SDK-1158: Introduced PR template.
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: improvement

#278 SDK-1273: Improved docker files
  bin/spryker-sdk.sh
  infrastructure/sdk.Dockerfile
  infrastructure/sdk.debug.Dockerfile
  infrastructure/sdk.local.Dockerfile
Labels: dev-qa done

#266 SDK-1064 implement ci telemetry
  app/Migrations/Version20221115141126.php
  composer.json
  composer.lock
  docker-compose.dev.yml
  docker-compose.rest-api.dev.yaml
  docker-compose.yml
  docs/telemetry.md
  infrastructure/env/.env
  src/Core/Application/Resources/config/services.yaml
  src/Core/Application/Telemetry/TelemetryEventMetadataFactory.php
  src/Core/Domain/Entity/Setting.php
  src/Core/Domain/Entity/SettingInterface.php
  src/Core/Domain/Entity/TelemetryEvent/TelemetryEventMetadata.php
  src/Core/Domain/Entity/TelemetryEvent/TelemetryEventMetadataInterface.php
  src/Extension/Resources/config/services.yaml
  src/Extension/Resources/config/setting/settings.yaml
  src/Extension/Setting/Initializer/ExecutionEnvInitializer.php
  src/Extension/Setting/Initializer/ProjectUuidInitializer.php
  src/Extension/Setting/Initializer/SdkUuidInitializer.php
  src/Infrastructure/Entity/Setting.php
  src/Infrastructure/Repository/SettingRepository.php
  src/Infrastructure/Resources/config/doctrine/Setting.orm.yml
  src/Infrastructure/Resources/config/services.yaml
  src/Infrastructure/Serializer/Normalizer/TelemetryEvent/TelemetryEventMetadataNormalizer.php
  src/Infrastructure/Service/Initializer.php
  src/Infrastructure/Setting/SettingFetcher.php
  tests/Sdk/Unit/Extension/Setting/Initializer/ExecutionEnvInitializerTest.php
  tests/Sdk/Unit/Extension/Setting/Initializer/SdkUuidInitializerTest.php
  tests/Sdk/Unit/Infrastructure/Service/InitializerTest.php
  tests/Sdk/Unit/Infrastructure/Setting/ProjectSettingsInitializer/ProjectSettingsInitializerTest.php
  tests/_support/Helper/Core/Application/Service/SettingManagerHelper.php
  tests/_support/UnitTester.php
Labels: dev-qa done, epic

#280 SDK-1267 fix a non-lazy commands loading bug
  src/Infrastructure/Collection/TaggedClassNameCollection/TaggedClassNameCollection.php
  src/Infrastructure/Collection/TaggedClassNameCollection/TaggedClassNameCollectionInterface.php
  src/Infrastructure/DependencyInjection/TaggedClassNameCollectionCompilerPass.php
  src/Infrastructure/Event/Telemetry/TelemetryConsoleEventListener.php
  src/Infrastructure/Event/Telemetry/TelemetryConsoleEventValidator.php
  src/Infrastructure/Logger/ErrorLoggerFactory.php
  src/Infrastructure/Logger/ErrorLoggerFactoryInterface.php
  src/Infrastructure/Resources/config/services.yaml
  src/Infrastructure/Service/ProjectInfo/ProjectInfoFetcher.php
  src/Infrastructure/SprykerSdkInfrastructureBundle.php
  src/Presentation/Console/Command/InitProjectCommand.php
  src/Presentation/Console/Command/QaAutomationCommand.php
  src/Presentation/Console/Resources/config/services.yaml
Labels: dev-qa done

#286 SDK-1325: Fixed mkdir for VCS clone
  src/Extension/Resources/config/services.yaml
  src/Extension/Task/Command/VcsCloneCommand.php
  src/Extension/Task/VcsCloneTask.php
Labels: bug, dev-qa done

#288 SDK-1328 update rest api doc
  docs/rest_api.md
Labels: documentation

#275 SDK-1110 add task placeholder generator
  assets/templates/manifest/task_manifest_template.php.twig
  assets/templates/manifest/task_manifest_template.yaml.twig
  composer.lock
  docs/extending_the_sdk.md
  src/Core/Application/Dto/Manifest/TaskManifestPlaceholderDto.php
  src/Core/Application/Dto/Manifest/TaskManifestRequestDto.php
  src/Core/Application/Registry/AbstractLazyRegistry.php
  src/Core/Application/Registry/RegistryInterface.php
  src/Core/Application/Registry/RegistryItemInterface.php
  src/Extension/Manifest/ValueResolver/ConfigPathValueResolverMap.php
  src/Extension/Manifest/ValueResolver/FlagValueResolverMap.php
  src/Extension/Manifest/ValueResolver/OriginValueResolverMap.php
  src/Extension/Manifest/ValueResolver/PriorityPathValueResolverMap.php
  src/Extension/Manifest/ValueResolver/StaticValueResolverMap.php
  src/Extension/Resources/config/services.yaml
  src/Extension/ValueResolver/ConfigPathValueResolver.php
  src/Extension/ValueResolver/FlagValueResolver.php
  src/Extension/ValueResolver/NamespaceValueResolver.php
  src/Extension/ValueResolver/OriginValueResolver.php
  src/Extension/ValueResolver/PriorityPathValueResolver.php
  src/Extension/ValueResolver/ReportDirValueResolver.php
  src/Extension/ValueResolver/SdkDirectoryValueResolver.php
  src/Extension/ValueResolver/StaticValueResolver.php
  src/Infrastructure/Manifest/Interaction/Config/ValueCollection.php
  src/Infrastructure/Manifest/Interaction/ManifestInteractionProcessor.php
  src/Infrastructure/Manifest/Interaction/Question/NewCollectionItemQuestion.php
  src/Infrastructure/Manifest/ManifestWriter/Task/FormatWriter/PhpTaskManifestFormatWriter.php
  src/Infrastructure/Manifest/Normalizer/ManifestNormalizerInterface.php
  src/Infrastructure/Manifest/Normalizer/PhpManifestNormalizer.php
  src/Infrastructure/Resources/config/services.yaml
  src/Infrastructure/Service/ValueResolverRegistry.php
  src/Infrastructure/Twig/Extension/ClassConstantFetcher.php
  src/Presentation/Console/Command/GenerateTaskCommand.php
  src/Presentation/Console/Manifest/Task/TaskInteractionMap.php
  src/Presentation/Console/Manifest/Task/TaskManifestRequestDtoFactory.php
  src/Presentation/Console/Manifest/Task/ValueResolver/ValueResolverMapInterface.php
  src/Presentation/Console/Manifest/Task/ValueResolver/ValuesResolverMapRegistry.php
  src/Presentation/Console/Manifest/Task/ValueResolver/ValuesResolverMapRegistryInterface.php
  src/Presentation/Console/Resources/config/services.yaml
  tests/Sdk/Unit/Infrastructure/Manifest/Interaction/ManifestInteractionProcessorTest.php
  tests/Sdk/Unit/Infrastructure/Manifest/Interaction/Question/NewCollectionItemQuestionTest.php
  tests/Sdk/Unit/Infrastructure/Manifest/ManifestWriter/Task/FormatWriter/PhpTaskManifestFormatWriterTest.php
  tests/Sdk/Unit/Presentation/Console/Manifest/Task/ValueResolver/ValuesResolverMapRegistryTest.php
Labels: dev-qa done

#289 SDK-1295: Added condition to check ENV setting and config
  bin/spryker-sdk.sh
Labels: dev-qa done

#284 SDK-1288 update exception message
  src/Infrastructure/Service/ProjectInfo/ComposerProjectInfoFetcher.php
  src/Presentation/Console/Command/RunWorkflowCommand.php
  src/Presentation/Console/Resources/config/services.yaml
Labels: dev-qa done
