Repository spryker-sdk/sdk, pull requests merged in 2022-10, with the labels that each got.

#227 SDK-988 self update script
  README.md
  infrastructure/installer_header.sh
Labels: dev-qa done

#225 SDK-986 update infrastructure
  .env
  .env.dist
  docker-compose.yml
  infrastructure/installer_header.sh
  infrastructure/sdk.Dockerfile
Labels: dev-qa done

#228 SDK-988: Structure SDK `.env` files and environment variables.
  .env.dist
  .env.prod
  docker-compose.debug.yml
  docker-compose.dev.yml
  docker-compose.yml
  docs/development.md
  infrastructure/.env
  infrastructure/installer_builder.sh
  infrastructure/sdk.Dockerfile
Labels: dev-qa done

#226 SDK-956: sdk validators
  composer.json
  composer.lock
  config/packages/workflow.yaml
  docs/conventions.md
  docs/manifest_validation.md
  docs/task.md
  extension/Hello/config/task/HelloTaskSet.yaml
  phpstan.neon
  src/Core/Application/Dependency/ManifestConfigurationInterface.php
  src/Core/Application/Dependency/ManifestValidatorInterface.php
  src/Core/Application/Dependency/Repository/TaskYamlRepositoryInterface.php
  src/Core/Application/Exception/ManifestValidatorMissingException.php
  src/Core/Application/Lifecycle/Subscriber/LifecycleEventSubscriber.php
  src/Core/Application/Resources/config/services.yaml
  src/Core/Domain/Enum/Lifecycle.php
  src/Core/Domain/Enum/Task.php
  src/Extension/Resources/config/task/AcpAppAsyncApiCodeGenerateTask.yaml
  src/Extension/Resources/config/task/AppValidationTaskSet.yaml
  src/Extension/Resources/config/task/RunInstallTask.yaml
  src/Infrastructure/Exception/InvalidConfigurationException.php
  src/Infrastructure/ManifestValidator/ManifestEntriesValidator.php
  src/Infrastructure/ManifestValidator/ManifestValidator.php
  src/Infrastructure/ManifestValidator/ManifestValidatorRegistry.php
  src/Infrastructure/ManifestValidator/TaskManifestConfiguration.php
  src/Infrastructure/ManifestValidator/TaskSetManifestConfiguration.php
  src/Infrastructure/Repository/TaskYamlRepository.php
  src/Infrastructure/Resources/config/services.yaml
  src/Infrastructure/Service/ErrorCommandListener.php
  src/Presentation/Console/Command/Validator/ValidateTaskCommand.php
  src/Presentation/Console/Resources/config/services.yaml
  tests/Sdk/Acceptance/Extension/Task/PhpStanTaskCest.php
  tests/Sdk/Acceptance/Presentation/Console/Command/Validator/ValidateTaskCommandCest.php
  tests/Sdk/Unit/Infrastructure/ManifestValidator/ManifestValidatorRegistryTest.php
  tests/Sdk/Unit/Infrastructure/ManifestValidator/ManifestValidatorTest.php
  tests/Sdk/Unit/Infrastructure/ManifestValidator/TaskManifestConfigurationTest.php
  tests/Sdk/Unit/Infrastructure/ManifestValidator/TaskSetManifestConfigurationTest.php
  tests/Sdk/Unit/Infrastructure/Repository/TaskYamlRepositoryTest.php
  tests/_support/data/WrongTask/HelloWorldTask.yaml
  tests/_support/data/WrongTask/SniffTaskSet.yaml
Labels: dev-qa done

#233 SDK-1009 update manifest validator
  src/Infrastructure/ManifestValidator/TaskManifestConfiguration.php
  src/Infrastructure/ManifestValidator/TaskSetManifestConfiguration.php
  src/Infrastructure/Repository/TaskYamlRepository.php
Labels: bug, dev-qa done

#246 SDK-1033 rid of unused prod files
  bin/spryker-sdk.sh
  docker-compose.yml
  infrastructure/.env
  infrastructure/installer_builder.sh
  infrastructure/sdk.Dockerfile
Labels: improvement

#237 SDK-1008 update dev env
  .env
  .env.dev
  .env.prod
  bin/spryker-sdk.sh
  docker-compose.debug.yml
  docker-compose.dev.yml
  docker-compose.yml
  docs/development.md
  docs/profiler.md
  infrastructure/debug/.bashrc
  infrastructure/debug/php/xhprof.ini
  infrastructure/debug/sdk.sh
  infrastructure/sdk.Dockerfile
  infrastructure/sdk.debug.Dockerfile
  src/Infrastructure/Event/Profiler/ProfilerEventListener.php
  src/Infrastructure/Resources/config/services.yaml
Labels: dev-qa done
