Repository spryker-sdk/sdk, pull requests merged in 2023-03, with the labels that each got.

#326 SDK-1769 Introduced the Newrelic extension.
  .env.sprykerci
  .github/workflows/post-release.yml
  config/packages/monolog.yaml
  docker-compose.yml
  infrastructure/newrelic/newrelic.ini
  infrastructure/sdk.sprykerci.Dockerfile
Labels: dev-qa done

#295 SDK-1356: version file usage and context
  bin/spryker-sdk.sh
  src/Core/Application/Cache/ContextCacheStorageInterface.php
  src/Core/Application/Dependency/ContextFactoryInterface.php
  src/Core/Application/Resources/config/services.yaml
  src/Core/Application/Service/ContextFactory.php
  src/Core/Application/Service/ContextSerializer.php
  src/Infrastructure/Cache/InMemoryContextCacheStorage.php
  src/Infrastructure/Repository/ContextFileRepository.php
  src/Infrastructure/Resources/config/services.yaml
  src/Infrastructure/Service/LifecycleManager.php
  src/Infrastructure/Telemetry/FileReportTelemetryEventSender.php
  src/Infrastructure/Version/FileAppVersionFetcher.php
  src/Presentation/Console/Command/AbstractUpdateCommand.php
  src/Presentation/Console/Command/QaAutomationCommand.php
  src/Presentation/Console/Command/RunTaskWrapperCommand.php
  src/Presentation/Console/Command/RunWorkflowCommand.php
  src/Presentation/Console/Command/UpdateCommand.php
  src/Presentation/Console/EventListener/ContextOutputCommandListener.php
  src/Presentation/Console/Resources/config/services.yaml
  src/Presentation/RestApi/Processor/RunTaskProcessor.php
  tests/Sdk/Unit/Core/Application/Service/ContextFactoryTest.php
  tests/Sdk/Unit/Infrastructure/Cache/InMemoryContextCacheStorageTest.php
  tests/Sdk/Unit/Infrastructure/Repository/ContextFileRepositoryTest.php
Labels: dev-qa done

#337 SDK-1948 update help message
  src/Extension/Resources/config/task/SprykRunTask.yaml
Labels: dev-qa done

#336 SDK-1975: Fixed checking all packages & improved reading composer.
  composer.lock
Labels: bug, improvement

#349 SDK-1799: Fixed relative path checks.
  src/Infrastructure/Service/ValueReceiver/QuestionFactory/PathQuestionFactory.php
  tests/Sdk/Unit/Infrastructure/Service/ValueReceiver/QuestionFactory/PathQuestionFactoryTest.php
Labels: bug

#333 SDK-2063: NR logger improvements.
  config/packages/monolog.yaml
  infrastructure/newrelic/entrypoint.sh
  infrastructure/newrelic/newrelic.ini
  infrastructure/sdk.sprykerci.Dockerfile
Labels: bug, dev-qa done
